//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_QuanLyLinhKien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public int MaSP { get; set; }
        public Nullable<int> TonKho { get; set; }
        public Nullable<int> TonKhoMin { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
