//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp_QuanLyLinhKien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public int KhoID { get; set; }
        public int SanPhamID { get; set; }
        public int SoLuongTon { get; set; }
        public Nullable<int> SoLuongToiThieu { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
